/**
 * Smoke test definitions — the WHAT (not the HOW).
 * Riley adds/edits tests here. The runner lives in tester.ts.
 */

export type CheckPattern = RegExp;
export type Category = 'core' | 'specialist' | 'tool-proof' | 'orchestration' | 'upgrades' | 'memory' | 'ux' | 'self-improvement' | 'infrastructure' | 'discord-management';
export type SmokeProfile = 'full' | 'readiness' | 'matrix';

export interface AgentCapabilityTest {
  id: string;
  category: Category;
  capability: string;
  prompt: string;
  expectAny?: CheckPattern[];
  expectAll?: CheckPattern[];
  expectNone?: CheckPattern[];
  requireTokenEcho?: boolean;
  expectToolAudit?: string[];
  expectUpgradesPost?: boolean;
  minBotRepliesAfterPrompt?: number;
  timeoutMs?: number;
  heavyTool?: boolean;
  /** Override per-test retry attempts (default: profile capabilityAttempts) */
  attempts?: number;
  /** If false, failure doesn't count toward critical gate (default: true) */
  critical?: boolean;
  /** If true, failure is tracked separately as flaky — doesn't block critical gate */
  flaky?: boolean;
}

export const AGENT_CAPABILITY_TESTS: AgentCapabilityTest[] = [
  {
    id: 'executive-assistant',
    category: 'core',
    capability: 'routing-and-next-step',
    prompt: 'Summarize your role in one sentence and give one concrete next step.',
    expectAny: [/next step|first step|action|recommend|priorit|suggest|should|plan|approach|focus|start|begin/i],
    requireTokenEcho: false,
  },
  {
    id: 'executive-assistant',
    category: 'memory',
    capability: 'repo-memory-tool-awareness',
    prompt: 'Name the two tools you should use to index and search repo memory before broad file scans.',
    expectAll: [/repo_memory_index/i, /repo_memory_search/i],
  },
  {
    id: 'executive-assistant',
    category: 'orchestration',
    capability: 'delegate-ace-qa',
    prompt: 'In a single reply, mention delegating a code task to Ace and a validation task to QA.',
    expectAny: [/ace|developer/i, /qa|max/i],
    requireTokenEcho: false,
    critical: false,
  },
  {
    id: 'executive-assistant',
    category: 'orchestration',
    capability: 'ace-only-delegation',
    prompt: 'You need security and QA help. Under your delegation policy you must route ALL execution through Ace only. Explain how you would delegate this through Ace in one short reply.',
    expectAny: [/ace|developer|delegat/i],
    expectNone: [/@kane|@max|@raj|@elena|@kai|@jude|@liv|@harper|@mia|@leo/i],
    requireTokenEcho: false,
    timeoutMs: 240_000,
  },
  {
    id: 'executive-assistant',
    category: 'memory',
    capability: 'repo-memory-evidence',
    prompt: 'Personally execute repo_memory_index and then repo_memory_search with query="setupChannels" right now (do NOT delegate). Reply with one source key or filename from the search results.',
    expectAny: [/setupchannels|channel|server|src|setup|source|key|file/i],
    expectToolAudit: ['repo_memory_index', 'repo_memory_search'],
    timeoutMs: 180_000,
  },

  {
    id: 'developer',
    category: 'core',
    capability: 'evidence-format-contract',
    prompt: 'Return ONLY this exact plain-text structure (no markdown headers):\nResult: <one sentence outcome>\nEvidence: <files changed or tests run>\nRisk/Follow-up: <caveats or next checks>',
    expectAll: [/\bresults?\s*:/i, /\bevidence\s*:/i, /\brisk|follow.?up/i],
  },
  {
    id: 'developer',
    category: 'tool-proof',
    capability: 'tool-audit-proof',
    prompt: 'Use read_file on server/package.json and search_files for quality script, then summarize in one line.',
    expectAny: [/quality|typecheck|lint|jest/i],
    expectToolAudit: ['read_file', 'search_files'],
  },
  {
    id: 'developer',
    category: 'upgrades',
    capability: 'upgrades-post',
    prompt: 'Use the send_channel_message tool to post one blocker-removal or token-saving improvement line in the #upgrades channel. You MUST include the exact smoke-token string in the message body.',
    expectUpgradesPost: true,
    timeoutMs: 180_000,
  },

  {
    id: 'qa',
    category: 'specialist',
    capability: 'regression-test-design',
    prompt: 'Provide one high-risk regression test for jobs matching in one sentence.',
    expectAny: [/regression|edge.?case|negative|timeout|retry|test|assert|expect|verif|valid|scenario|fail|bound/i],
  },
  {
    id: 'qa',
    category: 'tool-proof',
    capability: 'tool-audit-proof',
    prompt: 'Use list_threads and report one readiness signal in one sentence.',
    expectAny: [/thread|ready|active|idle/i],
    expectToolAudit: ['list_threads'],
  },
  {
    id: 'qa',
    category: 'upgrades',
    capability: 'upgrades-post',
    prompt: 'Post one test-automation enhancement in #upgrades and include the token exactly.',
    expectUpgradesPost: true,
  },

  {
    id: 'security-auditor',
    category: 'specialist',
    capability: 'auth-risk-and-mitigation',
    prompt: 'Name one auth vulnerability and one mitigation in one sentence.',
    expectAll: [/auth|token|session|jwt|password/i, /mitigat|prevent|rotate|validate|mfa/i],
  },
  {
    id: 'security-auditor',
    category: 'upgrades',
    capability: 'upgrades-post',
    prompt: 'Post one security-hardening upgrade in #upgrades and include the token exactly.',
    expectUpgradesPost: true,
  },

  {
    id: 'ux-reviewer',
    category: 'specialist',
    capability: 'a11y-priority',
    prompt: 'Name the single most important WCAG accessibility criterion to test first and explain why in one sentence.',
    expectAny: [/contrast|keyboard|screen.?reader|touch.?target|wcag|aria|focus|color|font|label|alt.?text|tab.?order|heading|semantic|navigation|landmark|role/i],
  },
  {
    id: 'api-reviewer',
    category: 'specialist',
    capability: 'http-semantics',
    prompt: 'What status code should be returned for missing resource?',
    expectAny: [/\b404\b/],
  },
  {
    id: 'dba',
    category: 'specialist',
    capability: 'postgres-safety',
    prompt: 'Name one PostgreSQL migration safety practice in one sentence.',
    expectAny: [/transaction|rollback|lock|backfill|index|migration|safe|wrap/i],
    timeoutMs: 240_000,
  },
  {
    id: 'performance',
    category: 'specialist',
    capability: 'measurement',
    prompt: 'Name one metric you would track first for app performance.',
    expectAny: [/latency|fps|memory|p95|p99|lighthouse|ttfb|throughput|response.?time|render|frame|time.?to.?first|tti|fcp|lcp|cls|inp|bundle|cpu|load|speed|perf|metric|network|request|duration|apdex|error.?rate|uptime/i],
    requireTokenEcho: false,
  },
  {
    id: 'devops',
    category: 'tool-proof',
    capability: 'tool-audit-proof',
    prompt: 'Run the gcp_run_describe tool now and summarize the deployment status in one sentence.',
    expectAny: [/cloud run|revision|traffic|ready|service|deploy|active|serving|running|status|gcp|container/i],
    expectToolAudit: ['gcp_run_describe'],
    timeoutMs: 180_000,
  },
  {
    id: 'copywriter',
    category: 'specialist',
    capability: 'microcopy-tone',
    prompt: 'Rewrite "Authentication failed" in a calm, user-friendly sentence.',
    expectAny: [/try again|please|check|couldn|unable/i],
  },
  {
    id: 'lawyer',
    category: 'specialist',
    capability: 'au-contractor-distinction',
    prompt: 'State one legal distinction between employee and contractor in Australia.',
    expectAny: [/control|independent|abn|super|entitlement|contractor|employ|worker|tax|leave|direction|hours|own tools|business|sham|fair work/i],
  },
  {
    id: 'ios-engineer',
    category: 'specialist',
    capability: 'ios-stack',
    prompt: 'Name the primary iOS language/framework in one sentence.',
    expectAny: [/swift|swiftui|uikit/i],
  },
  {
    id: 'android-engineer',
    category: 'specialist',
    capability: 'android-stack',
    prompt: 'Name the primary Android language/framework in one sentence.',
    expectAny: [/kotlin|jetpack|compose|gradle/i],
  },

  // ── Matrix-extended tests (26 additional tests) ──

  // Riley core: ACTION tags
  {
    id: 'executive-assistant',
    category: 'core',
    capability: 'action-status',
    prompt: 'Show current goal status and active threads.',
    expectAny: [/\[ACTION:STATUS\]|\[ACTION:THREADS\]|goal|status|thread|active/i],
  },
  {
    id: 'executive-assistant',
    category: 'core',
    capability: 'action-agents',
    prompt: 'List all available agents on this team.',
    expectAny: [/\[ACTION:AGENTS\]|ace|riley|kane|max|developer|qa/i],
  },
  {
    id: 'executive-assistant',
    category: 'core',
    capability: 'action-health',
    prompt: 'What is the current deployment health status? Reply directly without delegating.',
    expectAny: [/\[ACTION:HEALTH\]|health|cloud run|deployment|status|running|ready|online/i],
    timeoutMs: 150_000,
  },
  {
    id: 'executive-assistant',
    category: 'core',
    capability: 'action-urls',
    prompt: 'Show me the app URLs and Cloud Build console links.',
    expectAny: [/\[ACTION:URLS\]|url|console|cloud build|http/i],
    timeoutMs: 150_000,
  },
  {
    id: 'executive-assistant',
    category: 'core',
    capability: 'action-limits',
    prompt: 'Show the current budget and token usage.',
    expectAny: [/\[ACTION:LIMITS\]|budget|token|usage|limit/i],
    timeoutMs: 150_000,
  },
  {
    id: 'executive-assistant',
    category: 'core',
    capability: 'context-report',
    prompt: 'Show the current context efficiency.',
    expectAny: [/\[ACTION:CONTEXT\]|context|efficiency|token|usage/i],
    timeoutMs: 150_000,
  },

  // Ace developer: tool-proof tests
  {
    id: 'developer',
    category: 'tool-proof',
    capability: 'read-and-summarize',
    prompt: 'Use read_file to read server/src/routes/health.ts and summarize its exports in one line.',
    expectAny: [/health|export|route|function|handler/i],
    expectToolAudit: ['read_file'],
  },
  {
    id: 'developer',
    category: 'tool-proof',
    capability: 'search-codebase',
    prompt: 'Use search_files to find all Express route handlers that use authentication middleware, reply with one file path.',
    expectAny: [/server\/src\/routes|\.ts|auth|middleware/i],
    expectToolAudit: ['search_files'],
  },
  {
    id: 'developer',
    category: 'tool-proof',
    capability: 'typecheck-execution',
    prompt: 'Run typecheck on the server and report pass or fail in one line.',
    expectAny: [/pass|fail|error|success|clean|no issues/i],
    expectToolAudit: ['typecheck'],
    heavyTool: true,
  },
  {
    id: 'developer',
    category: 'tool-proof',
    capability: 'run-tests-execution',
    prompt: 'Use run_tests right now and report the result summary in one line.',
    expectAny: [/\d+\s*(pass|tests?|suites?|fail)|all.*pass|test.*completed|test.*ran|result.*test|passed|failed|success|jest|vitest|mocha|suite|spec|coverage/i],
    expectToolAudit: ['run_tests'],
    heavyTool: true,
    timeoutMs: 240_000,
  },
  {
    id: 'developer',
    category: 'specialist',
    capability: 'design-deliverable',
    prompt: 'Create a minimal health-check HTML snippet (just a div with id=\'status\' showing \'OK\') and return it. This is a design spec task.',
    expectAny: [/<div|id=.status.|OK|html/i],
  },
  {
    id: 'developer',
    category: 'tool-proof',
    capability: 'db-schema-inspect',
    prompt: 'Use db_schema to inspect the database and name three tables.',
    expectAny: [/table|schema|users|jobs|fuel/i],
    expectToolAudit: ['db_schema'],
  },
  {
    id: 'developer',
    category: 'tool-proof',
    capability: 'git-branch-awareness',
    prompt: "Use run_command to run 'git log --oneline -3' and summarize the last 3 commits.",
    expectAny: [/commit|merge|feat|fix|chore|refactor/i],
    expectToolAudit: ['run_command'],
  },

  // Security auditor: code review
  {
    id: 'security-auditor',
    category: 'tool-proof',
    capability: 'code-review',
    prompt: 'Use read_file to read server/src/routes/auth.ts and identify one security concern in one sentence.',
    expectAny: [/auth|security|vulnerab|inject|token|password|concern/i],
    expectToolAudit: ['read_file'],
  },

  // API reviewer: route review
  {
    id: 'api-reviewer',
    category: 'tool-proof',
    capability: 'route-review',
    prompt: 'Use search_files to find REST endpoint definitions in server/src/routes/ and name one that could benefit from pagination.',
    expectAny: [/pagina|limit|offset|cursor|page|endpoint|route/i],
    expectToolAudit: ['search_files'],
  },

  // DBA: schema inspect
  {
    id: 'dba',
    category: 'tool-proof',
    capability: 'schema-inspect',
    prompt: 'Use db_schema to list the tables in the database and name the one most likely to grow fastest.',
    expectAny: [/table|schema|grow|jobs|users|logs/i],
    expectToolAudit: ['db_schema'],
  },

  // Performance: code analysis
  {
    id: 'performance',
    category: 'tool-proof',
    capability: 'code-analysis',
    prompt: 'Use read_file on server/src/services/fuel.ts and identify one potential performance bottleneck in one sentence.',
    expectAny: [/performance|bottleneck|slow|optimi|cache|query|loop|n\+1/i],
    expectToolAudit: ['read_file'],
  },

  // DevOps: deployment inspect + gcp describe
  {
    id: 'devops',
    category: 'tool-proof',
    capability: 'deployment-inspect',
    prompt: 'Use gcp_list_revisions and report the latest revision name in one line. Prefix with TOOL_USED:gcp_list_revisions.',
    expectAll: [/TOOL_USED:gcp_list_revisions/i],
    expectAny: [/revision|rev-|deploy/i],
  },
  {
    id: 'devops',
    category: 'tool-proof',
    capability: 'gcp-describe',
    prompt: 'Use gcp_run_describe to check the current Cloud Run service and report its status in one line.',
    expectAny: [/cloud run|revision|ready|active|service|running/i],
  },

  // iOS: code read
  {
    id: 'ios-engineer',
    category: 'tool-proof',
    capability: 'code-read',
    prompt: 'Use search_files to find any Swift or SwiftUI references in the repository and report what you found in one line.',
    expectAny: [/swift|swiftui|found|no.*references|search|result/i],
    expectToolAudit: ['search_files'],
  },

  // Android: code read
  {
    id: 'android-engineer',
    category: 'tool-proof',
    capability: 'code-read',
    prompt: 'Use search_files to find any Kotlin or Jetpack Compose references in the repository and report what you found in one line.',
    expectAny: [/kotlin|compose|found|no.*references|search|result/i],
    expectToolAudit: ['search_files'],
  },

  // QA: run tests readonly
  {
    id: 'qa',
    category: 'tool-proof',
    capability: 'run-tests-readonly',
    prompt: 'Use run_tests to execute the test suite and report total pass count in one line.',
    expectAny: [/\d+\s*(pass|tests?|suites?)|all.*pass/i],
    expectToolAudit: ['run_tests'],
    heavyTool: true,
  },

  // Orchestration: delegate single specialist
  {
    id: 'executive-assistant',
    category: 'orchestration',
    capability: 'delegate-single-specialist',
    prompt: 'Ask Ace to review the auth route for security concerns.',
    expectAny: [/ace|developer|security|auth|review/i],
    minBotRepliesAfterPrompt: 1,
    requireTokenEcho: false,
  },
  // Orchestration: goal tracking
  {
    id: 'executive-assistant',
    category: 'orchestration',
    capability: 'goal-tracking',
    prompt: 'Give me the current status and any active goals right now.',
    expectAny: [/goal|status|active|none|no.*goal|tracking|idle/i],
    timeoutMs: 150_000,
  },
  // Memory: memory write
  {
    id: 'executive-assistant',
    category: 'memory',
    capability: 'memory-write',
    prompt: "Personally execute the memory_write tool right now (do NOT delegate this). Call it with file='smoke-test-note' and content='smoke test validated all agents'. You must actually invoke the function — do not just describe or claim to have done it. Reply 'done' only after seeing the tool result.",
    expectAny: [/memory|written|saved|confirmed|noted|stored|done/i],
    expectToolAudit: ['memory_write'],
    timeoutMs: 150_000,
    critical: false,
  },
  // Orchestration: specialist chain via Ace
  {
    id: 'developer',
    category: 'orchestration',
    capability: 'specialist-chain',
    prompt: 'Without using any tools, write a short paragraph explaining why auth route reviews should involve QA and security specialists. Keep it to 3-4 sentences.',
    expectAny: [/qa|security|review|specialist|audit/i],
    timeoutMs: 120_000,
    critical: false,
  },
  // Tool-proof: Riley job search profile + scan
  {
    id: 'executive-assistant',
    category: 'tool-proof',
    capability: 'job-search-profile',
    prompt: 'Use the job_profile_update tool right now to view my current job search profile (call it with no parameters). Then summarize what you see. Do NOT delegate this.',
    expectAny: [/profile|target.?role|salary|location|no.*profile|not.*set/i],
    expectToolAudit: ['job_profile_update'],
    timeoutMs: 150_000,
  },
  {
    id: 'executive-assistant',
    category: 'tool-proof',
    capability: 'job-tracker-summary',
    prompt: 'Use the job_tracker tool right now with action "summary" to check the current job pipeline status. Summarize the result. Do NOT delegate this.',
    expectAny: [/tracker|summary|scan|listing|no.*listing|total|pipeline|status|count/i],
    expectToolAudit: ['job_tracker'],
    timeoutMs: 150_000,
  },
  // Tool-proof: Riley job scan trigger
  {
    id: 'executive-assistant',
    category: 'tool-proof',
    capability: 'job-scan-trigger',
    prompt: 'Use the job_scan tool right now to scan for new job listings. Summarize what you find. Do NOT delegate this.',
    expectAny: [/scan|listing|found|job|role|no.*new|result|adzuna/i],
    expectToolAudit: ['job_scan'],
    timeoutMs: 180_000,
    heavyTool: true,
    attempts: 1,
  },
  // Tool-proof: Riley draft application
  {
    id: 'executive-assistant',
    category: 'tool-proof',
    capability: 'job-draft-application',
    prompt: 'Use the job_draft_application tool right now to draft an application for the most recently approved listing. If none are approved, say so. Do NOT delegate this.',
    expectAny: [/draft|cover.?letter|resume|application|no.*approved|no.*listing|not.*found/i],
    expectToolAudit: ['job_draft_application'],
    timeoutMs: 180_000,
    heavyTool: true,
    attempts: 1,
  },
  // Tool-proof: Riley submit application
  {
    id: 'executive-assistant',
    category: 'tool-proof',
    capability: 'job-submit-application',
    prompt: 'Use the job_submit_application tool right now to submit the most recently drafted application. If none are drafted, say so. Do NOT delegate this.',
    expectAny: [/submit|email|sent|greenhouse|no.*draft|manual|not.*found|no.*listing/i],
    expectToolAudit: ['job_submit_application'],
    timeoutMs: 180_000,
    heavyTool: true,
    attempts: 1,
  },
  // Tool-proof: Riley evaluate listing
  {
    id: 'executive-assistant',
    category: 'tool-proof',
    capability: 'job-evaluate-listing',
    prompt: 'Use the job_evaluate tool right now to evaluate any scanned but unevaluated listings. If there are none, say so. Do NOT delegate this.',
    expectAny: [/evaluat|score|fit|match|no.*listing|already.*evaluat|none|not.*found/i],
    expectToolAudit: ['job_evaluate'],
    timeoutMs: 180_000,
    heavyTool: true,
    attempts: 1,
  },
  // UX: Decision buttons render
  {
    id: 'executive-assistant',
    category: 'core',
    capability: 'decision-buttons-render',
    prompt: 'Post a decision to the decisions channel with two options: "Deploy now" and "Wait until tomorrow". Use numbered options like 1) Deploy now 2) Wait until tomorrow.',
    expectAny: [/decision|deploy|wait|option|posted|button/i],
    timeoutMs: 120_000,
  },
  // UX: Ops embed format
  {
    id: 'executive-assistant',
    category: 'core',
    capability: 'ops-embed-format',
    prompt: 'Give me a summary of current operational costs, active threads, and budget status. Respond directly with the information — do NOT delegate this to any specialist.',
    expectAny: [/cost|thread|spend|ops|status|budget/i],
    timeoutMs: 120_000,
  },

  // ── Goal lifecycle tests ──────────────────────────────────────────────
  {
    id: 'executive-assistant',
    category: 'core',
    capability: 'goal-create',
    prompt: 'Create a goal to audit the current test coverage and list gaps.',
    expectAny: [/goal|created|audit|coverage|started|tracking|thread|opened|working|task/i],
    timeoutMs: 180_000,
  },
  {
    id: 'executive-assistant',
    category: 'core',
    capability: 'goal-status-report',
    prompt: 'What goals are currently active? Report their status.',
    expectAny: [/active|in.progress|running|no.*active|goal|idle|none|status|tracking|thread|current|pending|queued|working/i],
    timeoutMs: 150_000,
  },
  {
    id: 'executive-assistant',
    category: 'core',
    capability: 'goal-stall-detection',
    prompt: 'Describe what happens when a goal stalls for more than 7 minutes with no progress. What mechanism detects and responds to this?',
    expectAny: [/stall|nudge|inactive|idle|timeout|watchdog/i],
    timeoutMs: 150_000,
  },
  {
    id: 'executive-assistant',
    category: 'core',
    capability: 'goal-completion',
    prompt: 'Start a goal to check TypeScript health, run typecheck, and mark the goal complete.',
    expectAny: [/complete|done|finished|closed|passed|clean/i],
    expectToolAudit: ['typecheck'],
    timeoutMs: 180_000,
  },

  // ── Thread lifecycle tests ────────────────────────────────────────────
  {
    id: 'executive-assistant',
    category: 'core',
    capability: 'thread-status-report',
    prompt: 'Use the list_threads tool to list all open threads, then report their age and activity status.',
    expectAny: [/thread|channel|open|active|age|idle|stale|list/i],
    expectToolAudit: ['list_threads'],
    timeoutMs: 150_000,
  },
  {
    id: 'executive-assistant',
    category: 'core',
    capability: 'thread-cleanup-awareness',
    prompt: 'Which threads are stale and should be closed? Explain the criteria you use.',
    expectAny: [/idle|stale|inactive|close|archive|old/i],
    timeoutMs: 120_000,
  },

  // ── Discord UX tests ─────────────────────────────────────────────────
  {
    id: 'executive-assistant',
    category: 'ux',
    capability: 'completion-embed',
    prompt: 'Create a goal to verify TypeScript compiles cleanly. Run typecheck, then close the thread when done.',
    expectAny: [/goal complete|complete|closed|clean|passed/i],
    expectToolAudit: ['typecheck'],
    timeoutMs: 240_000,
  },
  {
    id: 'executive-assistant',
    category: 'ux',
    capability: 'thread-name-quality',
    prompt: 'Hey Riley, can you please check if the search codebase tool is working correctly by searching for the main entry point?',
    expectAny: [/search|found|index|entry/i],
    expectNone: [/hey.*riley.*can.*you.*please/i],
    timeoutMs: 180_000,
  },
  {
    id: 'developer',
    category: 'ux',
    capability: 'file-change-preview',
    prompt: 'Edit the file src/discord/handlers/goalState.ts: add a comment "// UX smoke test" at the top of the file, then revert it immediately by removing that comment.',
    expectAny: [/edit|file|goalState|changed|reverted/i],
    expectToolAudit: ['edit_file'],
    timeoutMs: 180_000,
  },
  {
    id: 'developer',
    category: 'ux',
    capability: 'response-compaction',
    prompt: 'List every single file in the src/discord/ directory recursively and describe what each one does in detail. Be very thorough and verbose — include line counts, exports, and dependencies for each file.',
    expectAny: [/discord|handler|bot|claude|tester|agent/i],
    expectNone: [/undefined|error|cannot/i],
    timeoutMs: 180_000,
  },

  // ── System resilience tests ───────────────────────────────────────────
  {
    id: 'executive-assistant',
    category: 'core',
    capability: 'budget-exhaustion-awareness',
    prompt: 'What happens when the daily budget is exhausted? Describe your behavior.',
    expectAny: [/stop|pause|limit|budget|refuse|block/i],
    timeoutMs: 120_000,
  },
  {
    id: 'executive-assistant',
    category: 'core',
    capability: 'rate-limit-awareness',
    prompt: 'How do you handle API rate limits (429 responses)? Describe your retry strategy.',
    expectAny: [/retry|backoff|exponential|wait|delay/i],
    timeoutMs: 120_000,
  },
  {
    id: 'executive-assistant',
    category: 'core',
    capability: 'dedup-awareness',
    prompt: 'How do you handle duplicate messages sent within seconds of each other?',
    expectAny: [/dedup|ignore|skip|fingerprint|duplicate|discard/i],
    timeoutMs: 120_000,
  },

  // ── Upgrades triage tests ─────────────────────────────────────────────
  {
    id: 'executive-assistant',
    category: 'core',
    capability: 'upgrades-triage-digest',
    prompt: 'Summarize the current upgrades backlog. What are the top accepted items?',
    expectAny: [/accepted|deferred|backlog|upgrade|triage/i],
    timeoutMs: 150_000,
  },
  {
    id: 'executive-assistant',
    category: 'orchestration',
    capability: 'upgrades-act-on-top',
    prompt: 'Pick the highest-priority accepted upgrade from #upgrades and delegate its implementation to Ace.',
    expectAny: [/ace|delegate|implement|assign|@ace/i],
    timeoutMs: 180_000,
  },

  // ── Button UX validation ──────────────────────────────────────────────
  {
    id: 'executive-assistant',
    category: 'tool-proof',
    capability: 'job-buttons-approval',
    prompt: 'Execute the job_scan tool right now to scan for new job listings. If any results are found, also run job_post_approvals. Report what you found.',
    expectToolAudit: ['job_scan'],
    expectAny: [/scan|listings?|jobs?|found|no new|results?|search|role|position|opening|adzuna|match|pipeline|evaluat/i],
    timeoutMs: 180_000,
    heavyTool: true,
  },

  // ── Riley autonomy tests ──────────────────────────────────────────────
  {
    id: 'executive-assistant',
    category: 'tool-proof',
    capability: 'self-edit-file',
    prompt: 'Use your edit_file tool directly (do NOT delegate to Ace) to add a comment "// Riley was here" at the top of the file src/discord/tester.ts. Then use read_file to verify the change.',
    expectToolAudit: ['edit_file', 'read_file'],
    timeoutMs: 180_000,
    attempts: 1,
    flaky: true,
  },
  {
    id: 'executive-assistant',
    category: 'tool-proof',
    capability: 'create-branch-pr',
    prompt: `Use your git_create_branch tool directly (do NOT delegate to Ace) to create a branch called "riley/smoke-${Date.now()}". Then use edit_file to make a trivial change, run_command to commit and push, and create_pull_request to open a PR. Report the result.`,
    expectToolAudit: ['git_create_branch'],
    expectAny: [/branch|created|pull request|PR|pushed/i],
    timeoutMs: 240_000,
    heavyTool: true,
    attempts: 1,
    flaky: true,
  },
  {
    id: 'executive-assistant',
    category: 'orchestration',
    capability: 'review-ace-pr',
    prompt: 'Use your list_pull_requests tool directly to check for open PRs and report what you find. Do NOT delegate this task.',
    expectToolAudit: ['list_pull_requests'],
    timeoutMs: 180_000,
    attempts: 1,
  },

  // ── Web harness & verification tests ──────────────────────────────────
  {
    id: 'qa',
    category: 'tool-proof',
    capability: 'capture-screenshots-e2e',
    prompt: 'Use the capture_screenshots tool right now to capture the current state of the deployed app. Report how many screenshots were taken and whether the hero screen loaded.',
    expectAny: [/screenshot|capture|hero|screen|image|taken|posted/i],
    expectToolAudit: ['capture_screenshots'],
    timeoutMs: 180_000,
    heavyTool: true,
    attempts: 1,
    critical: false,
  },
  {
    id: 'qa',
    category: 'tool-proof',
    capability: 'mobile-harness-interactive',
    prompt: 'Use mobile_harness_start to open the app, then mobile_harness_snapshot to capture the current screen, then mobile_harness_stop to end the session. Report what you saw on screen.',
    expectAny: [/harness|session|screen|started|snapshot|stopped|mobile|viewport/i],
    expectToolAudit: ['mobile_harness_start', 'mobile_harness_snapshot', 'mobile_harness_stop'],
    timeoutMs: 180_000,
    heavyTool: true,
    attempts: 1,
    critical: false,
  },
  {
    id: 'executive-assistant',
    category: 'core',
    capability: 'verification-gate-awareness',
    prompt: 'When Ace claims a UI fix is done, what happens automatically before the thread can close? Describe the verification gate process.',
    expectAny: [/harness|screenshot|capture|evidence|verification|auto/i],
    timeoutMs: 120_000,
  },
  {
    id: 'executive-assistant',
    category: 'core',
    capability: 'thread-auto-close-review',
    prompt: 'Describe the automatic thread close review process. What triggers it, what does it check, and when does it close a thread automatically?',
    expectAny: [/stale|idle|inactive|auto.*close|review|archive|age|minutes|hours/i],
    timeoutMs: 120_000,
  },

  // ── Integration tests (end-to-end validation of critical paths) ────
  {
    id: 'developer',
    category: 'tool-proof',
    capability: 'edit-file-roundtrip',
    prompt: 'Do this exactly: 1) Use read_file on src/discord/tester.ts to read line 1. 2) Use edit_file to add "// integration-test-marker" as a new first line. 3) Use read_file again to confirm the edit is there. 4) Use edit_file to remove that "// integration-test-marker" line, reverting the file. 5) Report whether all 4 steps succeeded.',
    expectAny: [/success|completed|reverted|confirmed|all.*steps|done|passed|removed/i],
    expectToolAudit: ['edit_file', 'read_file'],
    timeoutMs: 240_000,
    heavyTool: true,
    attempts: 1,
    flaky: true,
  },
  {
    id: 'devops',
    category: 'tool-proof',
    capability: 'deployment-health-check',
    prompt: 'Use gcp_run_describe to check the Cloud Run service status, then use run_command to curl the health endpoint. Report whether the service is healthy with HTTP status.',
    expectAny: [/200|healthy|running|ready|serving|active|ok|up|alive/i],
    expectToolAudit: ['gcp_run_describe'],
    timeoutMs: 180_000,
  },
  {
    id: 'developer',
    category: 'core',
    capability: 'model-availability',
    prompt: 'Reply with exactly: "MODEL_OK" followed by the current date. This tests basic model response capability.',
    expectAny: [/MODEL_OK|model.ok|\d{4}/i],
    timeoutMs: 60_000,
    attempts: 1,
  },

  // ══════════════════════════════════════════════════════════════════════
  // ── FILE & CODE TOOLS (untested) ──────────────────────────────────────
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'developer',
    category: 'tool-proof',
    capability: 'write-file',
    prompt: 'Use write_file to create a new file at /tmp/smoke-write-test.txt with content "smoke test write OK". Then use read_file to verify it exists and contains that text. Report the result.',
    expectAny: [/write|created|smoke test write OK|verified|exists/i],
    expectToolAudit: ['write_file', 'read_file'],
    timeoutMs: 120_000,
  },
  {
    id: 'developer',
    category: 'tool-proof',
    capability: 'batch-edit',
    prompt: 'Use batch_edit to make two simultaneous edits: add a comment "// batch-test-A" at the top of src/discord/tester.ts AND a comment "// batch-test-B" at the top of src/discord/agents.ts. Then immediately revert both edits using batch_edit again. Report whether all steps succeeded.',
    expectAny: [/batch|edit|revert|success|done|completed/i],
    expectToolAudit: ['batch_edit'],
    timeoutMs: 180_000,
    heavyTool: true,
    flaky: true,
  },
  {
    id: 'developer',
    category: 'tool-proof',
    capability: 'check-file-exists',
    prompt: 'Use check_file_exists to verify that package.json exists and that nonexistent-file-xyz.ts does NOT exist. Report the results of both checks.',
    expectAny: [/exists|found|true|false|does not exist|not found/i],
    expectToolAudit: ['check_file_exists'],
    timeoutMs: 120_000,
  },
  {
    id: 'developer',
    category: 'tool-proof',
    capability: 'list-directory',
    prompt: 'Use list_directory to list the contents of src/discord/ and report how many files are in it.',
    expectAny: [/\d+\s*(file|item|entri)|bot\.ts|tester\.ts|agent|claude/i],
    expectToolAudit: ['list_directory'],
    timeoutMs: 120_000,
  },
  {
    id: 'developer',
    category: 'tool-proof',
    capability: 'git-file-history',
    prompt: 'Use git_file_history on src/discord/bot.ts and report the last 3 commit messages that changed this file.',
    expectAny: [/commit|history|change|fix|feat|refactor|add/i],
    expectToolAudit: ['git_file_history'],
    timeoutMs: 120_000,
  },
  {
    id: 'developer',
    category: 'tool-proof',
    capability: 'fetch-url',
    prompt: 'Use fetch_url to fetch https://asap-ud54h56rna-ts.a.run.app/ and report whether the page loaded successfully (check for status 200 or HTML content).',
    expectAny: [/200|html|loaded|success|ASAP|page|fetched/i],
    expectToolAudit: ['fetch_url'],
    timeoutMs: 120_000,
  },
  {
    id: 'developer',
    category: 'tool-proof',
    capability: 'github-search',
    prompt: 'Use github_search to search for "setupChannels" in the repository and report one file that contains it.',
    expectAny: [/setup|channel|found|file|result|match/i],
    expectToolAudit: ['github_search'],
    timeoutMs: 120_000,
  },

  // ── GIT & PR WORKFLOW ─────────────────────────────────────────────────
  {
    id: 'developer',
    category: 'tool-proof',
    capability: 'add-pr-comment',
    prompt: 'Use list_pull_requests to find any open PRs. If one exists, use add_pr_comment to add a comment "smoke test review pass". If none exist, report that.',
    expectAny: [/comment|PR|pull request|no.*open|added|posted|none/i],
    expectToolAudit: ['list_pull_requests'],
    timeoutMs: 120_000,
    critical: false,
  },

  // ── DATABASE TOOLS ────────────────────────────────────────────────────
  {
    id: 'dba',
    category: 'tool-proof',
    capability: 'db-query-readonly',
    prompt: 'Use db_query_readonly to run "SELECT COUNT(*) as total FROM users" and report the result.',
    expectAny: [/\d+|total|count|rows|users|result|empty/i],
    expectToolAudit: ['db_query_readonly'],
    timeoutMs: 120_000,
  },
  {
    id: 'dba',
    category: 'tool-proof',
    capability: 'db-query-write-safety',
    prompt: 'IMPORTANT: Do NOT actually run a destructive query. Instead: 1) Use db_query_readonly to SELECT one row from any table. 2) Explain what safeguards prevent accidental data deletion via db_query. Report the result and safeguards.',
    expectAny: [/safeguard|transaction|rollback|permission|readonly|restrict|protect|prevent/i],
    expectToolAudit: ['db_query_readonly'],
    timeoutMs: 120_000,
  },

  // ── MEMORY & KNOWLEDGE TOOLS ──────────────────────────────────────────
  {
    id: 'executive-assistant',
    category: 'memory',
    capability: 'memory-read',
    prompt: 'Use memory_read to read the file "smoke-test-note" that was written earlier. Report what it contains. Do NOT delegate this.',
    expectAny: [/smoke|test|validated|content|memory|read|not found|empty/i],
    expectToolAudit: ['memory_read'],
    timeoutMs: 120_000,
    critical: false,
  },
  {
    id: 'executive-assistant',
    category: 'memory',
    capability: 'memory-append',
    prompt: 'Use memory_append to add a line "smoke test append check" to the file "smoke-test-note". Then use memory_read to verify it was appended. Do NOT delegate this.',
    expectAny: [/append|added|verified|confirmed|smoke test append/i],
    expectToolAudit: ['memory_append'],
    timeoutMs: 120_000,
    critical: false,
  },
  {
    id: 'executive-assistant',
    category: 'memory',
    capability: 'memory-list',
    prompt: 'Use memory_list to list all memory files. Report how many exist and name at least one. Do NOT delegate this.',
    expectAny: [/\d+\s*(file|item|memor)|smoke|list|found/i],
    expectToolAudit: ['memory_list'],
    timeoutMs: 120_000,
    critical: false,
  },
  {
    id: 'executive-assistant',
    category: 'memory',
    capability: 'repo-memory-add-oss',
    prompt: 'Use repo_memory_add_oss to index knowledge about the discord.js library (just the library name and version). Report what was indexed. Do NOT delegate this.',
    expectAny: [/discord\.js|indexed|added|oss|knowledge|library/i],
    expectToolAudit: ['repo_memory_add_oss'],
    timeoutMs: 120_000,
    critical: false,
  },

  // ══════════════════════════════════════════════════════════════════════
  // ── DISCORD MANAGEMENT TOOLS ──────────────────────────────────────────
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'executive-assistant',
    category: 'discord-management',
    capability: 'list-channels',
    prompt: 'Use list_channels to list all channels in this Discord server. Report the count and name at least 3 channels. Do NOT delegate this.',
    expectAny: [/\d+\s*(channel|text)|groupchat|terminal|upgrades|channel/i],
    expectToolAudit: ['list_channels'],
    timeoutMs: 120_000,
  },
  {
    id: 'executive-assistant',
    category: 'discord-management',
    capability: 'send-channel-message',
    prompt: 'Use send_channel_message to post "smoke test channel message OK" in the #terminal channel. Report success. Do NOT delegate this.',
    expectAny: [/sent|posted|message|terminal|success|done/i],
    expectToolAudit: ['send_channel_message'],
    timeoutMs: 120_000,
  },
  {
    id: 'executive-assistant',
    category: 'discord-management',
    capability: 'set-channel-topic',
    prompt: 'Use set_channel_topic to set the topic of #terminal to "Smoke test verified". Then report what the topic was set to. Do NOT delegate this.',
    expectAny: [/topic|set|terminal|smoke test verified|updated/i],
    expectToolAudit: ['set_channel_topic'],
    timeoutMs: 120_000,
    critical: false,
  },
  {
    id: 'executive-assistant',
    category: 'discord-management',
    capability: 'create-rename-delete-channel',
    prompt: 'Do these steps in order: 1) Use create_channel to create a text channel called "smoke-test-temp". 2) Use rename_channel to rename it to "smoke-test-renamed". 3) Use delete_channel to delete the renamed channel. Report whether all 3 steps succeeded. Do NOT delegate this.',
    expectAny: [/created|renamed|deleted|success|all.*steps|completed|done/i],
    expectToolAudit: ['create_channel'],
    timeoutMs: 180_000,
    heavyTool: true,
    critical: false,
  },

  // ══════════════════════════════════════════════════════════════════════
  // ── INFRASTRUCTURE & GCP TOOLS ────────────────────────────────────────
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'devops',
    category: 'infrastructure',
    capability: 'gcp-preflight',
    prompt: 'Use gcp_preflight to check GCP project access and permissions. Report the result. Are we ready to deploy?',
    expectAny: [/preflight|project|permission|access|ready|gcp|asap/i],
    expectToolAudit: ['gcp_preflight'],
    timeoutMs: 120_000,
  },
  {
    id: 'devops',
    category: 'infrastructure',
    capability: 'gcp-build-status',
    prompt: 'Use gcp_build_status to check the most recent Cloud Build. Report its status (success/failure/in-progress).',
    expectAny: [/build|status|success|fail|progress|complete|cloud build/i],
    expectToolAudit: ['gcp_build_status'],
    timeoutMs: 120_000,
  },
  {
    id: 'devops',
    category: 'infrastructure',
    capability: 'gcp-get-env',
    prompt: 'Use gcp_get_env to read the current Cloud Run environment configuration. Report how many env vars are set (do NOT reveal secrets).',
    expectAny: [/\d+\s*(env|var|config)|environment|configuration|set|configured/i],
    expectToolAudit: ['gcp_get_env'],
    timeoutMs: 120_000,
  },
  {
    id: 'devops',
    category: 'infrastructure',
    capability: 'gcp-logs-query',
    prompt: 'Use gcp_logs_query to fetch the last 10 Cloud Run log entries. Report whether the service is logging normally (check for errors).',
    expectAny: [/log|entries|normal|error|healthy|running|cloud run/i],
    expectToolAudit: ['gcp_logs_query'],
    timeoutMs: 120_000,
  },
  {
    id: 'devops',
    category: 'infrastructure',
    capability: 'read-logs',
    prompt: 'Use read_logs to check the most recent Cloud Run application logs. Report whether there are any errors or warnings.',
    expectAny: [/log|error|warning|clean|healthy|normal|no.*error/i],
    expectToolAudit: ['read_logs'],
    timeoutMs: 120_000,
  },
  {
    id: 'devops',
    category: 'infrastructure',
    capability: 'gcp-project-info',
    prompt: 'Use gcp_project_info to get information about the GCP project. Report the project ID and region.',
    expectAny: [/project|asap|region|australia|gcp|id/i],
    expectToolAudit: ['gcp_project_info'],
    timeoutMs: 120_000,
  },
  {
    id: 'devops',
    category: 'infrastructure',
    capability: 'gcp-storage-ls',
    prompt: 'Use gcp_storage_ls to list GCS buckets or contents. Report what storage is available.',
    expectAny: [/bucket|storage|gs:|gcs|list|found|empty/i],
    expectToolAudit: ['gcp_storage_ls'],
    timeoutMs: 120_000,
  },
  {
    id: 'devops',
    category: 'infrastructure',
    capability: 'gcp-artifact-list',
    prompt: 'Use gcp_artifact_list to list container images in Artifact Registry. Report the most recent image tag.',
    expectAny: [/artifact|image|tag|registry|container|docker|latest/i],
    expectToolAudit: ['gcp_artifact_list'],
    timeoutMs: 120_000,
  },
  {
    id: 'devops',
    category: 'infrastructure',
    capability: 'gcp-sql-describe',
    prompt: 'Use gcp_sql_describe to describe the Cloud SQL instance. Report the instance name and status.',
    expectAny: [/sql|instance|database|postgres|running|status|name/i],
    expectToolAudit: ['gcp_sql_describe'],
    timeoutMs: 120_000,
  },
  {
    id: 'devops',
    category: 'infrastructure',
    capability: 'gcp-secret-list',
    prompt: 'Use gcp_secret_list to list the secrets configured in Secret Manager. Report how many secrets exist (do NOT reveal values).',
    expectAny: [/\d+\s*(secret|key|config)|secret.*manager|listed|found/i],
    expectToolAudit: ['gcp_secret_list'],
    timeoutMs: 120_000,
  },
  {
    id: 'devops',
    category: 'infrastructure',
    capability: 'gcp-vm-ssh',
    prompt: 'Use gcp_vm_ssh to connect to the bot VM and run "uptime". Report the VM uptime. Do NOT restart anything.',
    expectAny: [/uptime|day|hour|minute|load|up/i],
    expectToolAudit: ['gcp_vm_ssh'],
    timeoutMs: 180_000,
    heavyTool: true,
  },

  // ══════════════════════════════════════════════════════════════════════
  // ── SELF-IMPROVEMENT & AUTONOMOUS CAPABILITY ──────────────────────────
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'executive-assistant',
    category: 'self-improvement',
    capability: 'identify-blocker',
    prompt: 'Analyze the current codebase and identify one concrete blocker, bug, or limitation that is reducing team efficiency. Use read_file or search_files to gather evidence. Propose a specific fix. Do NOT delegate — do this yourself.',
    expectAny: [/blocker|bug|limitation|issue|problem|fix|improvement|propose|found/i],
    expectToolAudit: ['read_file'],
    timeoutMs: 180_000,
  },
  {
    id: 'executive-assistant',
    category: 'self-improvement',
    capability: 'propose-upgrade',
    prompt: 'Look at the current #upgrades backlog and the codebase. Propose one new upgrade that would improve the Discord bot capabilities — something not already proposed. Write a concrete implementation plan. Post it to #upgrades. Do NOT delegate.',
    expectAny: [/upgrade|improvement|proposal|new.*capability|implement|plan|posted/i],
    expectUpgradesPost: true,
    timeoutMs: 180_000,
  },
  {
    id: 'executive-assistant',
    category: 'self-improvement',
    capability: 'implement-fix-autonomously',
    prompt: 'Find one small, safe improvement to make in the codebase (a comment cleanup, a missing type annotation, or a TODO that can be resolved). Use edit_file to make the fix, then use typecheck to verify you did not break anything. Report what you changed and the typecheck result. Do NOT delegate.',
    expectAny: [/edit|changed|fixed|typecheck|pass|clean|improved/i],
    expectToolAudit: ['edit_file', 'typecheck'],
    timeoutMs: 240_000,
    heavyTool: true,
    flaky: true,
  },
  {
    id: 'developer',
    category: 'self-improvement',
    capability: 'refactor-proposal',
    prompt: 'Use search_files to find the largest file in src/discord/ (by looking for complex files with many functions). Propose one concrete refactoring to improve its maintainability. Show the specific code section and what you would change.',
    expectAny: [/refactor|extract|split|simplif|modular|function|class|file|large|complex/i],
    expectToolAudit: ['search_files'],
    timeoutMs: 180_000,
  },
  {
    id: 'developer',
    category: 'self-improvement',
    capability: 'fix-and-verify',
    prompt: 'Run typecheck to check for any type errors. If any exist, use edit_file to fix one, then run typecheck again to verify the fix. If none exist, report "clean typecheck". Show before/after.',
    expectAny: [/clean|fixed|error|pass|typecheck|no.*error|resolved/i],
    expectToolAudit: ['typecheck'],
    timeoutMs: 240_000,
    heavyTool: true,
  },
  {
    id: 'developer',
    category: 'self-improvement',
    capability: 'add-missing-test',
    prompt: 'Use search_files to find a function in src/discord/ that lacks test coverage. Propose a specific test case for it (describe the test, input, expected output). Do NOT write the test file — just describe what should be tested.',
    expectAny: [/test|coverage|function|assert|expect|should|describe|input|output/i],
    expectToolAudit: ['search_files'],
    timeoutMs: 180_000,
  },
  {
    id: 'executive-assistant',
    category: 'self-improvement',
    capability: 'deploy-self-gated',
    prompt: 'Describe the self-deploy process: what checks run before gcp_deploy is allowed to proceed? What happens if typecheck or run_tests fail? Do NOT actually deploy — just describe the safety gates.',
    expectAny: [/typecheck|run_tests|gate|block|fail|check|safety|test.*pass|verify/i],
    timeoutMs: 120_000,
  },
  {
    id: 'executive-assistant',
    category: 'self-improvement',
    capability: 'set-daily-budget',
    prompt: 'Use set_daily_budget to report the current daily budget setting. Do NOT change it — just read/report the current value. Do NOT delegate.',
    expectAny: [/budget|\$|\d+|daily|limit|current|set/i],
    expectToolAudit: ['set_daily_budget'],
    timeoutMs: 120_000,
    critical: false,
  },

  // ══════════════════════════════════════════════════════════════════════
  // ── SPECIALIST DEEP-DIVE (under-tested agents) ────────────────────────
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'copywriter',
    category: 'specialist',
    capability: 'onboarding-copy',
    prompt: 'Write onboarding welcome text for a new user joining the ASAP app for the first time. Keep it under 50 words, warm and professional.',
    expectAny: [/welcome|get started|ready|excited|glad|here to help|journey/i],
  },
  {
    id: 'copywriter',
    category: 'specialist',
    capability: 'error-message-audit',
    prompt: 'Use read_file to read server/src/routes/auth.ts and identify one user-facing error message that could be improved. Rewrite it in a friendlier tone.',
    expectAny: [/error|message|rewrite|friendly|try|please|sorry/i],
    expectToolAudit: ['read_file'],
    timeoutMs: 120_000,
  },
  {
    id: 'lawyer',
    category: 'specialist',
    capability: 'privacy-compliance',
    prompt: 'Does the ASAP app collect user data? If so, name one Australian Privacy Principle (APP) that applies and what we must do to comply.',
    expectAny: [/APP|privacy|principle|collection|consent|notice|disclosure|data|personal information/i],
  },
  {
    id: 'lawyer',
    category: 'specialist',
    capability: 'terms-review',
    prompt: 'What are three essential clauses that must be in our Terms of Service for an Australian SaaS app?',
    expectAny: [/term|clause|liability|warranty|termination|dispute|governing law|indemnity|license/i],
  },
  {
    id: 'security-auditor',
    category: 'specialist',
    capability: 'owasp-top-10',
    prompt: 'Name the top 3 OWASP Top 10 risks most relevant to this application and explain one mitigation for each.',
    expectAny: [/injection|broken.*auth|access.*control|misconfiguration|XSS|SSRF|OWASP|A0[1-9]/i],
  },
  {
    id: 'security-auditor',
    category: 'tool-proof',
    capability: 'dependency-scan',
    prompt: 'Use run_command to run "npm audit --json | head -50" and summarize the security vulnerabilities found. Report critical and high severity counts.',
    expectAny: [/vulnerabilit|critical|high|moderate|low|audit|clean|found|npm/i],
    expectToolAudit: ['run_command'],
    timeoutMs: 120_000,
  },
  {
    id: 'api-reviewer',
    category: 'specialist',
    capability: 'api-versioning',
    prompt: 'Review the API routes in the codebase. Is there a versioning strategy (e.g., /api/v1/)? If not, propose one.',
    expectAny: [/version|v1|v2|api|prefix|breaking|backward/i],
  },
  {
    id: 'api-reviewer',
    category: 'tool-proof',
    capability: 'endpoint-audit',
    prompt: 'Use search_files to find all Express route definitions (app.get, app.post, router.get, router.post) and count how many endpoints exist. Report the count and list the first 5.',
    expectAny: [/\d+\s*(endpoint|route)|GET|POST|PUT|DELETE|route|endpoint/i],
    expectToolAudit: ['search_files'],
    timeoutMs: 120_000,
  },
  {
    id: 'performance',
    category: 'specialist',
    capability: 'bundle-analysis',
    prompt: 'What techniques should be used to reduce the client bundle size of a React Native app? Name 3 specific strategies.',
    expectAny: [/tree.?shak|lazy|split|dynamic|import|bundle|minif|compress|optimize|reduce/i],
  },
  {
    id: 'performance',
    category: 'tool-proof',
    capability: 'database-query-perf',
    prompt: 'Use db_schema to inspect the database and identify one table that would benefit from an additional index. Recommend the index.',
    expectAny: [/index|query|performance|scan|slow|column|table|optimize/i],
    expectToolAudit: ['db_schema'],
    timeoutMs: 120_000,
  },
  {
    id: 'ux-reviewer',
    category: 'specialist',
    capability: 'color-contrast',
    prompt: 'What is the minimum WCAG AA contrast ratio for normal text and for large text? State both numbers.',
    expectAny: [/4\.5|3\.0|3:1|4\.5:1|contrast|ratio/i],
  },
  {
    id: 'ux-reviewer',
    category: 'tool-proof',
    capability: 'app-ux-audit',
    prompt: 'Use fetch_url to load the ASAP app at https://asap-ud54h56rna-ts.a.run.app/ and identify one UX improvement opportunity from the HTML content.',
    expectAny: [/UX|improvement|accessibility|usability|navigation|layout|button|font|color|user/i],
    expectToolAudit: ['fetch_url'],
    timeoutMs: 120_000,
  },
  {
    id: 'ios-engineer',
    category: 'specialist',
    capability: 'ios-permissions',
    prompt: 'Name 3 iOS permissions commonly needed by a job-finding app and explain one gotcha with the App Store review process.',
    expectAny: [/permission|notification|location|camera|photo|plist|review|rejection|privacy/i],
  },
  {
    id: 'ios-engineer',
    category: 'tool-proof',
    capability: 'ios-code-review',
    prompt: 'Use search_files to find any React Native bridge or native module code and report whether there are iOS-specific native modules in the project.',
    expectAny: [/native|module|bridge|react native|found|no.*native|swift|objective/i],
    expectToolAudit: ['search_files'],
    timeoutMs: 120_000,
  },
  {
    id: 'android-engineer',
    category: 'specialist',
    capability: 'android-permissions',
    prompt: 'Name 3 Android runtime permissions commonly needed by a job-finding app and explain the permission request flow.',
    expectAny: [/permission|location|notification|camera|storage|manifest|runtime|request|grant/i],
  },
  {
    id: 'android-engineer',
    category: 'tool-proof',
    capability: 'android-build-review',
    prompt: 'Use search_files to find any Gradle build files or Android-specific configuration in the project. Report what you found.',
    expectAny: [/gradle|android|build|manifest|found|no.*android|config|eas/i],
    expectToolAudit: ['search_files'],
    timeoutMs: 120_000,
  },

  // ══════════════════════════════════════════════════════════════════════
  // ── DELEGATION & ORCHESTRATION (end-to-end chains) ────────────────────
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'executive-assistant',
    category: 'orchestration',
    capability: 'multi-agent-chain',
    prompt: 'I need a security review of the auth routes. Delegate to Ace to read the auth code, then have him share findings with the security specialist (via you). Report back the chain of actions taken.',
    expectAny: [/ace|delegate|security|auth|review|finding|chain|specialist/i],
    minBotRepliesAfterPrompt: 2,
    timeoutMs: 240_000,
    critical: false,
  },
  {
    id: 'executive-assistant',
    category: 'orchestration',
    capability: 'error-recovery',
    prompt: 'Delegate a task to Ace to read a file that does not exist: "nonexistent-smoke-test-file-xyz.ts". When Ace reports the error, explain how you handle the failure and what your next step would be.',
    expectAny: [/error|not found|fail|recover|retry|alternative|handle|does not exist/i],
    minBotRepliesAfterPrompt: 1,
    timeoutMs: 180_000,
    critical: false,
  },
  {
    id: 'executive-assistant',
    category: 'orchestration',
    capability: 'rapid-dedup',
    prompt: 'This is a duplicate check. If you see this prompt twice in quick succession, you should only respond once. Acknowledge this message.',
    expectAny: [/acknowledge|understood|noted|received|ok|got it/i],
    timeoutMs: 60_000,
    critical: false,
  },

  // ══════════════════════════════════════════════════════════════════════
  // ── UPGRADES CHANNEL (additional agents) ──────────────────────────────
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'ux-reviewer',
    category: 'upgrades',
    capability: 'upgrades-post',
    prompt: 'Post one UX/accessibility improvement recommendation in #upgrades. Include the token exactly.',
    expectUpgradesPost: true,
    timeoutMs: 120_000,
  },
  {
    id: 'performance',
    category: 'upgrades',
    capability: 'upgrades-post',
    prompt: 'Post one performance optimization recommendation in #upgrades. Include the token exactly.',
    expectUpgradesPost: true,
    timeoutMs: 120_000,
  },
  {
    id: 'devops',
    category: 'upgrades',
    capability: 'upgrades-post',
    prompt: 'Post one infrastructure or deployment improvement in #upgrades. Include the token exactly.',
    expectUpgradesPost: true,
    timeoutMs: 120_000,
  },

  // ══════════════════════════════════════════════════════════════════════
  // ── REMAINING TOOL COVERAGE (destructive tools tested via safety gates)
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'executive-assistant',
    category: 'discord-management',
    capability: 'clear-channel-messages-safety',
    prompt: 'Use clear_channel_messages to clear the #terminal channel of any smoke test messages. Report how many messages were deleted. Do NOT delegate.',
    expectAny: [/clear|delete|removed|\d+\s*message|done|terminal|cleaned/i],
    expectToolAudit: ['clear_channel_messages'],
    timeoutMs: 120_000,
    critical: false,
  },
  {
    id: 'devops',
    category: 'infrastructure',
    capability: 'gcp-build-image',
    prompt: 'Use gcp_build_image to trigger a Cloud Build for the current codebase. Report the build ID and initial status. If the build is already running, report that instead.',
    expectAny: [/build|trigger|id|status|started|running|queued|already/i],
    expectToolAudit: ['gcp_build_image'],
    timeoutMs: 180_000,
    heavyTool: true,
    critical: false,
    flaky: true,
  },
  {
    id: 'devops',
    category: 'infrastructure',
    capability: 'gcp-deploy-safety',
    prompt: 'Describe what happens when you call gcp_deploy. What pre-checks run automatically (typecheck, run_tests)? What blocks the deploy if they fail? Do NOT actually deploy — just describe the safety gates by calling gcp_preflight first.',
    expectAny: [/typecheck|run_tests|gate|block|check|safety|preflight|test.*pass|verify/i],
    expectToolAudit: ['gcp_preflight'],
    timeoutMs: 120_000,
  },
  {
    id: 'devops',
    category: 'infrastructure',
    capability: 'gcp-set-env-safety',
    prompt: 'Use gcp_get_env to read the current env vars, then explain what would happen if you used gcp_set_env to change one. What safeguards exist? Do NOT actually change anything.',
    expectAny: [/env|variable|safeguard|rollback|change|config|review|careful/i],
    expectToolAudit: ['gcp_get_env'],
    timeoutMs: 120_000,
  },
  {
    id: 'devops',
    category: 'infrastructure',
    capability: 'gcp-list-revisions',
    prompt: 'Use gcp_list_revisions to list all Cloud Run revisions. Report how many exist and which is serving traffic.',
    expectAny: [/revision|traffic|serving|\d+|active|list/i],
    expectToolAudit: ['gcp_list_revisions'],
    timeoutMs: 120_000,
  },
  {
    id: 'devops',
    category: 'infrastructure',
    capability: 'gcp-rollback-awareness',
    prompt: 'Describe the gcp_rollback process. Which revision would you roll back to and why? Use gcp_list_revisions to check what revisions exist. Do NOT actually rollback.',
    expectAny: [/rollback|revision|previous|traffic|revert|version/i],
    expectToolAudit: ['gcp_list_revisions'],
    timeoutMs: 120_000,
  },
  {
    id: 'devops',
    category: 'infrastructure',
    capability: 'gcp-secret-management',
    prompt: 'Use gcp_secret_list to list secrets, then explain how gcp_secret_set and gcp_secret_bind work to manage secrets. Do NOT create or modify any secrets.',
    expectAny: [/secret|bind|set|manage|version|service/i],
    expectToolAudit: ['gcp_secret_list'],
    timeoutMs: 120_000,
  },
  {
    id: 'developer',
    category: 'tool-proof',
    capability: 'create-pull-request',
    prompt: 'Use list_pull_requests to check for open PRs. Then explain what parameters create_pull_request requires (title, body, base, head). If a smoke branch exists, use create_pull_request to open a PR from it. Otherwise, report that no branch is ready.',
    expectAny: [/pull request|PR|title|body|base|head|branch|created|no.*branch|open/i],
    expectToolAudit: ['list_pull_requests'],
    timeoutMs: 120_000,
    critical: false,
  },
  {
    id: 'executive-assistant',
    category: 'tool-proof',
    capability: 'merge-pr-awareness',
    prompt: 'Use list_pull_requests to check for open PRs. Explain what checks you perform BEFORE using merge_pull_request (typecheck, tests, review). Do NOT actually merge anything. Report what PRs exist.',
    expectAny: [/merge|check|typecheck|test|review|PR|pull request|open|none/i],
    expectToolAudit: ['list_pull_requests'],
    timeoutMs: 120_000,
  },
  {
    id: 'developer',
    category: 'tool-proof',
    capability: 'add-pr-comment-direct',
    prompt: 'Use list_pull_requests to find any open PRs. If one exists, use add_pr_comment to post "Smoke test automated review". If none, report that.',
    expectAny: [/comment|PR|pull request|no.*open|added|posted|none/i],
    expectToolAudit: ['list_pull_requests'],
    timeoutMs: 120_000,
    critical: false,
  },
  {
    id: 'qa',
    category: 'tool-proof',
    capability: 'mobile-harness-step',
    prompt: 'Use mobile_harness_start to open the app, then mobile_harness_step with action "tap" on the first button visible on screen, then mobile_harness_snapshot to capture the result, then mobile_harness_stop. Report the interaction result.',
    expectAny: [/harness|tap|button|step|interaction|screen|started|stopped/i],
    expectToolAudit: ['mobile_harness_start', 'mobile_harness_step', 'mobile_harness_snapshot', 'mobile_harness_stop'],
    timeoutMs: 180_000,
    heavyTool: true,
    attempts: 1,
    critical: false,
  },
  {
    id: 'executive-assistant',
    category: 'tool-proof',
    capability: 'job-post-approvals',
    prompt: 'Use job_post_approvals to post any pending job listings for approval in Discord. If none are pending, report that. Do NOT delegate.',
    expectAny: [/approval|posted|pending|no.*pending|none|listing|button/i],
    expectToolAudit: ['job_post_approvals'],
    timeoutMs: 120_000,
    critical: false,
  },
  {
    id: 'dba',
    category: 'tool-proof',
    capability: 'db-query-insert-safety',
    prompt: 'Use db_query_readonly to count rows in the users table. Then explain what safeguards exist around db_query for write operations (transactions, permissions, validation). Do NOT run any write queries.',
    expectAny: [/safeguard|transaction|rollback|permission|validation|write|protect|\d+/i],
    expectToolAudit: ['db_query_readonly'],
    timeoutMs: 120_000,
  },
  {
    id: 'executive-assistant',
    category: 'tool-proof',
    capability: 'smoke-test-agents-awareness',
    prompt: 'Explain what the smoke_test_agents tool does and which profiles are available (readiness, matrix, full). How would you trigger it if asked to run a test? Do NOT actually run it.',
    expectAny: [/smoke|test|readiness|matrix|full|profile|agent|trigger/i],
    timeoutMs: 120_000,
  },

  // --- Structure & Navigation Tests ---
  {
    id: 'executive-assistant',
    category: 'core',
    capability: 'repo-map-navigation',
    prompt: 'Read .github/REPO_MAP.md and tell me: where do I add a new smoke test? Which file, and what does an entry look like?',
    expectAny: [/test-definitions\.ts|AGENT_CAPABILITY_TESTS|expectAny|capability/i],
    expectToolAudit: ['read_file'],
    timeoutMs: 120_000,
  },
  {
    id: 'executive-assistant',
    category: 'core',
    capability: 'personality-awareness',
    prompt: 'Read .github/riley-personality.md and describe your communication style in 2-3 sentences. What does "aesthetic taste" mean for you?',
    expectAny: [/channel|aesthetic|taste|concise|direct|teammate|warm|emoji|clean|tidy/i],
    expectToolAudit: ['read_file'],
    timeoutMs: 120_000,
  },
  {
    id: 'executive-assistant',
    category: 'core',
    capability: 'memory-file-awareness',
    prompt: 'Read .github/riley-memory.md and list 3 Discord channel categories from your channel map.',
    expectAny: [/groupchat|agent workspace|operations|personal|career|announcements|terminal/i],
    expectToolAudit: ['read_file'],
    timeoutMs: 120_000,
  },
];

export const READINESS_TEST_KEYS = new Set([
  'executive-assistant:routing-and-next-step',
  'executive-assistant:repo-memory-tool-awareness',
  'executive-assistant:ace-only-delegation',
  'developer:evidence-format-contract',
  'developer:upgrades-post',
  'qa:regression-test-design',
  'qa:upgrades-post',
  'security-auditor:auth-risk-and-mitigation',
  'security-auditor:upgrades-post',
  'ux-reviewer:a11y-priority',
  'api-reviewer:http-semantics',
  'dba:postgres-safety',
  'performance:measurement',
  'devops:tool-audit-proof',
  'copywriter:microcopy-tone',
  'lawyer:au-contractor-distinction',
  'ios-engineer:ios-stack',
  'android-engineer:android-stack',
]);

export function testKey(test: AgentCapabilityTest): string {
  return `${test.id}:${test.capability}`;
}
